#### GENERAL
spring.application.name=books-api
server.port=${SERVER_PORT:8081}

spring.jackson.property-naming-strategy=SNAKE_CASE

#### GUTENDEX API
gutendex.url=https://gutendex.com/books

resilience4j.retry.instances.gutendex.maxAttempts=3
resilience4j.retry.instances.gutendex.waitDuration=200ms
resilience4j.retry.instances.gutendex.enableExponentialBackoff=true
resilience4j.retry.instances.gutendex.exponentialBackoffMultiplier=1.5

resilience4j.retry.instances.gutendex.ignoreExceptions[0]=org.springframework.web.client.HttpClientErrorException

#### REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:morotech}
spring.data.redis.password=${REDIS_PASSWORD:red!!sbo0kSS}

spring.data.redis.timeout=${REDIS_TIMEOUT:1s}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:1s}
spring.cache.redis.time-to-live=10m

app.cache.key-prefix=${ENVIRONMENT:staging}:${spring.application.name}

#### LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

####  DB
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:2345}/${DATABASE_NAME:books-db}
spring.datasource.username=${DATABASE_USERNAME:morotech}
spring.datasource.password=${DATABASE_PASSWORD:m0r0tecH!!}
spring.datasource.driver-class-name=org.postgresql.Driver