name: books-api-infra

services:

  # # # # # # # # # # # # #
  books-db:
    image: postgres:latest
    container_name: books-db
    ports: [ "2345:5432" ]
    environment:
      POSTGRES_USER: morotech
      POSTGRES_PASSWORD: m0r0tecH!!
      POSTGRES_DB: books-db
    volumes:
      - books_postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U morotech -d books-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # # # # # # # # # # # # #
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports: [ "6379:6379" ]
    volumes:
      - ../cache/users.acl:/usr/local/etc/redis/users.acl:ro
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --aclfile /usr/local/etc/redis/users.acl
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  books_postgres_data: